
export const GTO_PREFLOP_VALUES =[
    27,
    19,
    7.5,
    17,
    22,
    38,
    30,
    82,
    9,
    50,
    9,
    22,
    11,
    16,
    23,
    32,
    52,
    35,
    8,
    13,
    8.5,
    24
];
export const GTO_PREFLOP_KEYS = [
        "VPIP",
        "PFR",
        "3Bet",
        "Fold to 3Bet IP",
        "Fold to 3Bet OOP",
        "Fold to Squeeze As Raiser",
        "Fold to 4Bet",
        "SB Fold to BTN Steal",
        "SB Resteal vs BTN",
        "BB Fold to BTN Steal",
        "BB Resteal vs BTN Steal",
        "BB Fold to SB Steal",
        "3Bet in BB vs SB",
        "Early RFI",
        "Middle RFI",
        "Cutoff RFI",
        "Button RFI",
        "SB Steal",
        "SB Open Limp",
        "BTN Cold Call",
        "BTN 3Bet vs CO",
        "BTN Fold to 4Bet IP"

    ];