export const GTO_MIDSTAKES_PREFLOP_VALUES = [
    27,
    19,
    7.5,
    17,
    22,
    38,
    30,
    82,
    9,
    50,
    9,
    22,
    11,
    16,
    23,
    32,
    52,
    35,
    8,
    13,
    8.5,
    24
];

export const GTO_POSTFLOP_AS_TITLES = [
    "Flop Agg%",
    "Turn Agg%",
    "River Agg%",
    "WTSD%",
    "W$WSF",
    "W$WSF Rating",
    "Flop CBet Single Rsd Pot IP",
    "Flop CBet-Fold IP Single Raised",
    "Skip Flop CBet and Fold To Turn Bet IP",
    "Flop CBet Single Rsd Pot vs 2 Opps Success%",
    "Turn CBet Single Rsd Pot IP",
    "Turn CBet-Fold IP Single Raised",
    "Skip Turn CBet - Fold River SRP IP",
    "River CBet Single Rsd Pot IP",
    "Delayed Turn CBet IP SRP",
    "Flop CBet Single Rsd Pot OOP",
    "Flop CBet-Fold Single Rsd Pot",
    "Skip Flop CBet and Check-Fold - Single Rsd Pot OOP",
    "Skip Flop CBet and Check-Raise - Single Rsd Pot OOP",
    "Turn CBet Single Rsd Pot OOP",
    "Turn CBet-Fold OOP Single Raised",
    "Skip Turn CBet and Check-Fold OOP Single Rsd Pot",
    "River CBet Single Rsd Pot OOP",
    "Skip River CBet and Check-Fold OOP Single Rsd Pot",
    "Flop CBet 3BetPot IP",
    "Flop CBet-Fold IP 3Bet Pot",
    "Flop CBet 3BetPot OOP",
    "Flop CBet-Fold OOP 3Bet Pot",
    "Skip Flop CBet and Check-Fold - 3Bet Pot OOP",
    "Skip Flop CBet and Check-Raise - 3Bet Pot OOP",
    "Turn CBet 3BetPot IP",
    "Skip Turn CBet - Fold River 3Bet+ Pot IP",
    "Turn CBet 3BetPot OOP",
    "Skip Turn CBet - Check Fold 3Bet+ Pot OOP",
];

export const GTO_POSTFLOP_AS_VALUES = [
    34,
    32,
    31,
    32,
    48,
    1.08,
    52,
    42,
    42,
    25,
    48,
    45,
    53,
    47,
    40,
    20,
    48,
    37,
    11,
    35,
    45,
    47,
    45,
    55,
    60,
    40,
    70,
    30,
    40,
    12,
    55,
    50,
    45,
    50
];

export const GTO_POSTFLOP_VS_TITLES = [
    "Flop Fold vs CBet Rsd IP",
    "Flop Raise vs CBet Rsd IP",
    "Bet vs Missed CBet IP SRP ",
    "Turn Fold vs CBet Rsd IP",
    "River Fold vs CBet Rsd IP",
    "Flop Donk Bet SRP",
    "Flop Donk Bet-Fold",
    "Flop Check-Fold vs CBet Raised OOP",
    "Flop Check-Raise vs CBet Raised OOP",
    "Turn Bet vs Missed Flop CBet OOP",
    "Turn Check-Fold OOP to Delayed CBet SRP",
    "River Check-Fold vs CBet Raised OOP",
    "Flop Fold vs CBet 3Bet IP",
    "Flop Raise vs CBet 3Bet IP",
    "Flop Bet vs Missed CBet 3Bet Pot",
    "Flop Check-Fold vs CBet 3Bet OOP",
    "Flop Check-Raise - 3Bet Pot OOP",
    "Turn Bet vs Missed CBet (Duplicate - Beta only)"
];

export const GTO_POSTFLOP_VS_VALUES = [
    37,
    9,
    40,
    35,
    50,
    15,
    45,
    42,
    12,
    35,
    45,
    45,
    50,
    42,
    18,
    45,
    40,
    18,
    38
];
export const GTO_PREFLOP_KEYS = [
    "VPIP",
    "PFR",
    "3Bet",
    "Fold to 3Bet IP",
    "Fold to 3Bet OOP",
    "Fold to Squeeze As Raiser",
    "Fold to 4Bet",
    "SB Fold to BTN Steal",
    "SB Resteal vs BTN",
    "BB Fold to BTN Steal",
    "BB Resteal vs BTN Steal",
    "BB Fold to SB Steal",
    "3Bet in BB vs SB",
    "Early RFI",
    "Middle RFI",
    "Cutoff RFI",
    "Button RFI",
    "SB Steal",
    "SB Open Limp",
    "BTN Cold Call",
    "BTN 3Bet vs CO",
    "BTN Fold to 4Bet IP"
];
export const GTO_KEYS = [
    "VPIP",
    "PFR",
    "3Bet",
    "Fold to 3Bet IP",
    "Fold to 3Bet OOP",
    "Fold to Squeeze As Raiser",
    "Fold to 4Bet",
    "SB Fold to BTN Steal",
    "SB Resteal vs BTN",
    "BB Fold to BTN Steal",
    "BB Resteal vs BTN Steal",
    "BB Fold to SB Steal",
    "3Bet in BB vs SB",
    "Early RFI",
    "Middle RFI",
    "Cutoff RFI",
    "Button RFI",
    "SB Steal",
    "SB Open Limp",
    "BTN Cold Call",
    "BTN 3Bet vs CO",
    "BTN Fold to 4Bet IP",
    "Flop Agg%",
    "Turn Agg%",
    "River Agg%",
    "WTSD%",
    "W$WSF",
    "W$WSF Rating",
    "Flop CBet Single Rsd Pot IP",
    "Flop CBet-Fold IP Single Raised",
    "Skip Flop CBet and Fold To Turn Bet IP",
    "Flop CBet Single Rsd Pot vs 2 Opps Success%",
    "Turn CBet Single Rsd Pot IP",
    "Turn CBet-Fold IP Single Raised",
    "Skip Turn CBet - Fold River SRP IP",
    "River CBet Single Rsd Pot IP",
    "Delayed Turn CBet IP SRP",
    "Flop CBet Single Rsd Pot OOP",
    "Flop CBet-Fold Single Rsd Pot",
    "Skip Flop CBet and Check-Fold - Single Rsd Pot OOP",
    "Skip Flop CBet and Check-Raise - Single Rsd Pot OOP",
    "Turn CBet Single Rsd Pot OOP",
    "Turn CBet-Fold OOP Single Raised",
    "Skip Turn CBet and Check-Fold OOP Single Rsd Pot",
    "River CBet Single Rsd Pot OOP",
    "Skip River CBet and Check-Fold OOP Single Rsd Pot",
    "Flop CBet 3BetPot IP",
    "Flop CBet-Fold IP 3Bet Pot",
    "Flop CBet 3BetPot OOP",
    "Skip Flop CBet and Check-Fold - 3Bet Pot OOP",
    "Flop CBet-Fold 3BetPot",
    "Skip CBet and Fold 3Bet+ Pot",
    "Skip Flop CBet and Check-Raise - 3Bet Pot OOP",
    "Turn CBet 3BetPot IP",
    "Skip Turn CBet - Fold River 3Bet+ Pot IP",
    "Turn CBet 3BetPot OOP",
    "Skip Turn CBet - Check Fold 3Bet+ Pot OOP",
    "Flop Fold vs CBet Rsd IP",
    "Flop Raise vs CBet Rsd IP",
    "Bet vs Missed CBet IP SRP ",
    "Turn Fold vs CBet Rsd IP",
    "River Fold vs CBet Rsd IP",
    "Flop Donk Bet SRP",
    "Flop Donk Bet-Fold",
    "Flop Check-Fold vs CBet Raised OOP",
    "Flop Check-Raise vs CBet Raised OOP",
    "Turn Bet vs Missed Flop CBet OOP",
    "Turn Check-Fold vs CBet Raised OOP",
    "Turn Check-Fold OOP to Delayed CBet SRP",
    "River Check-Fold vs CBet Raised OOP",
    "Flop Fold vs CBet 3Bet IP",
    "Flop Raise vs CBet 3Bet IP",
    "Flop Bet vs Missed CBet 3Bet Pot",
    "Flop Check-Fold vs CBet 3Bet OOP",
    "Flop Check-Raise - 3Bet Pot OOP",
    "Turn Bet vs Missed CBet (Duplicate - Beta only)"
];
