  name: CI

  on:
    push:
      branches: [ main ]
    pull_request:
      branches: [ main ]

  jobs:
    build:
      runs-on: ubuntu-latest

      strategy:
        matrix:
          node-version: [18, 20]

      steps:
        - uses: actions/checkout@v4

        - name: Use Node.js ${{ matrix.node-version }}
          uses: actions/setup-node@v4
          with:
            node-version: ${{ matrix.node-version }}
            cache: 'npm'

        - name: Install dependencies
          run: npm ci

        - name: Run linter (if present)
          run: npm run lint --if-present

        - name: Build
          run: npm run build --if-present

        - name: Test
          run: npm test -- --coverage --watchAll=false

        - name: Upload coverage
          uses: actions/upload-artifact@v4
          with:
            name: coverage-${{ matrix.node-version }}
            path: coverage/